databases:
  - name: beenzen_home_project
    databaseName: beenzen_home_project
    user: beenzen_home_project
    plan: free

services:
  - type: web
    name: beenzen_home_project
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: beenzen_home_project
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
